export const LOAD_RESERVATIONS_SUCCESS = 'LOAD_RESERVATIONS_SUCCESS';
export const LOAD_SERVICES_SUCCESS = 'LOAD_SERVICES_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const INSERT_RESERVATIONS_SUCCESS = 'INSERT_RESERVATIONS_SUCCESS';
export const INSERT_SERVICES_SUCCESS = 'INSERT_SERVICES_SUCCESS';
export const INSERT_USERS_SUCCESS = 'INSERT_USERS_SUCCESS';

export const INSERT_RESERVATIONS_ERROR = 'INSERT_RESERVATIONS_ERROR';
export const INSERT_SERVICES_ERROR = 'INSERT_SERVICES_ERROR';
export const INSERT_USERS_ERROR = 'INSERT_USERS_ERROR';

export const EDIT_RESERVATIONS_SUCCESS = 'EDIT_RESERVATIONS_SUCCESS';
export const EDIT_SERVICES_SUCCESS = 'EDIT_SERVICES_SUCCESS';
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS';

export const DELETE_RESERVATIONS_SUCCESS = 'DELETE_RESERVATIONS_SUCCESS';
export const DELETE_SERVICES_SUCCESS = 'DELETE_SERVICES_SUCCESS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';

export const JOIN_RESERVATION_USER_SUCCESS = 'JOIN_RESERVATION_USER_SUCCESS';
